# store your custom template at foo/bar/database.yml.erb
set :template_dir, "config"
#
# example of database template

development:
  database: db/development.sqlite3
  adapter: sqlite3
  timeout: 5000
test:
  database: db/test.sqlite3
  adapter: sqlite3
  timeout: 5000
#production:
#  adapter: mysql2
#  database: db/production.sqlite3
#  username: root
#  password: root
#  encoding: utf8
#  timeout: 5000
